// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh61Ahe7Z_ve4WpFxy1IlgBRDgYwwJoxE',
    appId: '1:856955801114:web:0a742e1f0d3ceab4ad0ba3',
    messagingSenderId: '856955801114',
    projectId: 'demand-app1',
    authDomain: 'demand-app1.firebaseapp.com',
    storageBucket: 'demand-app1.appspot.com',
    measurementId: 'G-5GR336X10Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONYkYoeFHuJsGQXNVBFq0GQLymMwtsaE',
    appId: '1:856955801114:android:2df807ebd1f4054bad0ba3',
    messagingSenderId: '856955801114',
    projectId: 'demand-app1',
    storageBucket: 'demand-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhIqFkjRLVmKaRj43NeYeR7vg9T_S99g',
    appId: '1:856955801114:ios:6c9a4e8097f4811ead0ba3',
    messagingSenderId: '856955801114',
    projectId: 'demand-app1',
    storageBucket: 'demand-app1.appspot.com',
    iosBundleId: 'com.example.my1App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWhIqFkjRLVmKaRj43NeYeR7vg9T_S99g',
    appId: '1:856955801114:ios:6c9a4e8097f4811ead0ba3',
    messagingSenderId: '856955801114',
    projectId: 'demand-app1',
    storageBucket: 'demand-app1.appspot.com',
    iosBundleId: 'com.example.my1App',
  );
}
